# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu2204"
  config.vm.synced_folder "/scratch", "/host_scratch", :mount_options => ['dmode=774','fmode=775']
  config.vm.synced_folder "../..", "/vagrant"

  config.vm.provider "virtualbox" do |lv|
    lv.memory = 6144
    lv.cpus = 4
  end

  config.vm.provision "shell", inline: <<-SHELL
      apt-get update
      apt-get install -y software-properties-common
      apt-get upgrade -y
      apt-add-repository ppa:apptainer/ppa
      apt-get update
      apt-get install -y apptainer
  SHELL
end
